name: boti_lints
description: Um pacote de lints customizados para projetos Boti.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  custom_lint_builder: ^0.6.4
  bloc: any

dev_dependencies:
  lints: ^3.0.0
