name: boti_lints
description: Um pacote de lints customizados para projetos Boti.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  analyzer: any
  custom_lint_builder: ^0.8.0
  bloc: any

dev_dependencies:
  lints: any
