name: boti_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.1
  custom_lint_builder: ^0.6.4
  bloc: any

dev_dependencies:
  lints: ^5.0.0
  custom_lint: ^0.6.4
  test: ^1.24.0
  flutter_test:
    sdk: flutter
