name: meu_exemplo
description: A sample command-line application to test my llint rules.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: any

dev_dependencies:
  boti_lints:
    path: ../../
